### PR TITLE
Removed the array warnings

### PR DESCRIPTION
**Pull request by ashfaqnisar**
Modified the code to remove the array callback values

### CODE REVIEW

**Comment by xprilion** [comment]
Thanks for the fix @ashfaqnisar!

I tried running it locally and got this - 

```
index.js:1 Warning: Failed prop type: Invalid prop `elevation` of type `string` supplied to `ForwardRef(Paper)`, expected `number`.
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (at App.js:140)
    in footer (at App.js:139)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at App.js:96)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at App.js:95)
    in App (created by WithStyles(App))
    in WithStyles(App) (at src/index.js:13)
    in ThemeProvider (at src/index.js:12)
```

can you please check?

**Comment by xprilion** [comment]
Looks like something to do with my own code, I'll fix that as well with this!

**Comment by xprilion** [comment]
@all-contributors please add @ashfaqnisar for code

**Comment by ashfaqnisar** [comment]
> 
> 
> Looks like something to do with my own code, I'll fix that as well with this!

Awesome @xprilion

**Pull request merged**
